### ISSUE TITLE
Question: Recommended way to check state of command window

### ISSUE THREAD

**Issue by acook** [Ratamacue9112/CopperDC#2]
I want to control which scripts are accepting input at any given time, and when the CopperDC command window is accepting input I want other nodes to ignore input.

I've looked through the code to see that Copper checks `$"Command Field"` visibility when toggling, but that node doesn't seem to be accessible from other functions I've created.

```GDScript
func debug_console_is_visible():
	var debug_console_node = $"Command Field"
	return is_instance_valid(debug_console_node) && debug_console_node.get_visible()
```

Is there a more reliable way that you recommend?

**Comment by Ratamacue9112** [comment]
That seems to be the best way to do it currently. I'll probably add some sort of built-in variable or function just to make it more convenient.

**Comment by acook** [comment]
Maybe my setup is broken, but the standard dollar-sign syntax isn't working for me, it always returns null. I ended up using `get_node` and pulling the exact path from the root in order to get the reference and check the state. `get_visible()` also doesn't work on that node, but just checking the `visible` member works fine.

Hopefully this *working* (Godot 4.2.1) code will help out anyone with a similar use case:

```gdscript
@onready var debug_console_node = get_node("/root/debug_console/Command Field")

func debug_console_is_visible() -> bool:
	if is_instance_valid(debug_console_node):
		return debug_console_node.visible
	else:
		return false
```

**Comment by Ratamacue9112** [comment]
I've now implemented a function that does this called `is_console_visible`. Hope it works for you.
